import Head from 'next/head'
import Image from 'next/image'
import Navbar from '../components/Navbar/Navbar'
import SideDrawer from '../components/Navbar/SideDrawer'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div>
      <Navbar></Navbar>
      <SideDrawer></SideDrawer>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    </div>
  )
}
